general.import = [
    "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12

[font.normal]
family = "JetBrainsMonoNerdFontMono"
style = "Regular"

[font.italic]
family = "JetBrainsMonoNerdFontMono"
style = "Italic"

[font.bold]
family = "JetBrainsMonoNerdFontMono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMonoNerdFontMono"
style = "Bold Italic"

[window]
opacity=0.7
